### ISSUE TITLE
Persist custom composer dependencies

### ISSUE THREAD

**Issue by scottrigby** [bitnami/bitnami-docker-drupal#93] opened 2018-07-23 18:22 UTC
**Description**

Since the image allows mounting custom modules, and Drupal uses the [Composer Merge Plugin](https://github.com/wikimedia/composer-merge-plugin) to merge module dependencies into the top-level `/vendor` directory (and updates the `composer.json`, `composer.lock`, and `autoload.php` files), those requires composer changes don't currently persist in this image. See [Managing dependencies for a contributed project](https://www.drupal.org/docs/develop/using-composer/managing-dependencies-for-a-contributed-project) for more info about this functionality.

**Steps to reproduce the issue:**

1. Add a module that requires a composer dependency
2. Use drush to install the module
3. Confirm the dependencies autoload correctly
4. Rebuild the container (if on k8s, delete the pod so the pod/container recreates)

**Describe the results you received:**

The Drupal database still attempts to load the dependencies but throws a fatal error that the classes are not found (because they are no longer in the `/vendor` dir or defined in the composer autoload file).

**Describe the results you expected:**

The dependencies continue to autoload correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

The `/vendor` directory, `composer.json`, `composer.lock`, and `autoload.php` files should be symlinked into `/opt/bitnami/drupal` just like `modules`, `profiles`, `sites` and `themes` currently are.

**Comment by carrodher** [comment] 2018-07-24 07:16
Thanks for report the issue, as you said, currently we're persisting the following directories:
`sites`, `themes`, `modules` and `profiles`

**Comment by scottrigby** [comment] 2018-07-24 17:52
@carrodher I could exec into the container and copy those files & directory to `/bitnami/drupal`, then create symlinks myself to those in `opt/bitnami/drupal`, but AFAIK it won't help the existing init scripts you have which will write over `opt/bitnami/drupal` during container re/create. If you have other ideas for this though, I'll try them.

**Comment by marcosbc** [comment] 2018-07-25 09:35
Hi @scottrigby,

Unfortunately we don't have an estimation for when we will implement this, but in the meantime, there are many ways to workaround it.

For example, you can try persisting the vendor directory after the first boot:

- Start your docker-compose installation, and move `vendor` to the persist directory by running the command below inside your Drupal container:

      $ mv /opt/bitnami/drupal/vendor /bitnami/drupal

- Stop the docker-compose installation.
- Create the following files, which will allow you to create a new custom container:

  - `Dockerfile`

        FROM bitnami/drupal:8

        COPY custom-app-entrypoint.sh /

        ENTRYPOINT ["/custom-app-entrypoint.sh"]
        CMD ["./run.sh"]

  - `custom-app-entrypoint.sh`

        #!/bin/bash -e

        if [ -d /bitnami/drupal/vendor ]
        then
            echo "Creating vendor symlink"
            rm -rf /opt/bitnami/drupal/vendor
            ln -s /bitnami/drupal/vendor /opt/bitnami/drupal/vendor
        fi

        exec /app-entrypoint.sh "$@"

- Build the new container:

      $ docker build -t mydrupal .


- Edit your `docker-compose.yml` file:

      --- a/docker-compose.yml
      +++ b/docker-compose.yml
      @@ -10,7 +10,7 @@ services:
           volumes:
             - 'mariadb_data:/bitnami'
         drupal:
      -    image: 'bitnami/drupal:8'
      +    image: 'mydrupal'
           labels:
             kompose.service.type: nodeport
           environment:

- Start the docker-compose installation, and your vendor directory should now be persisted after each restart.

I hope this works for you!

**Comment by scottrigby** [comment] 2018-08-13 21:46
Hi @marcosbc that works manually because the drupal data temporarily persists in a volume set by docker-compose… but because of the way `app-entrypoint.sh` works, I'm not clear on how you would do this programmatically in a Docker image that would be compatible with kubernetes. 

As a test, I added this line between `nami_initialize apache php mysql-client drupal` and `exec tini -- "$@"`:
```sh
until [ -f /bitnami/drupal/.initialized ]; do echo Drupal is initializing...; sleep 5; done; echo Drupal has been initialized.;
```
so that I could know when drupal has been fully installed before creating the symlinks (so we don't interrupt the Drupal installation process accidentally while creating the custom symlinks). Somehow this never completed. Do you have any suggestions? It's been fun but time consuming to reverse-engineer this image…

**Comment by marcosbc** [comment] 2018-08-16 15:49
Hi @scottrigby,

That change works properly for us. However, by modifying the `app-entrypoint.sh`, you could programatically create the `vendor` symlink.

Find an `app-entrypoint.sh` example below that creates the `vendor` symlink automatically during the first initialization:

```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]; then
  . /init.sh
  nami_initialize apache php mysql-client drupal
  until [ -f /bitnami/drupal/.initialized ]; do
    echo Drupal is still initializing...
    sleep 5
  done
  echo Drupal has been initialized.;
  if [ -d /bitnami/drupal/vendor ]; then
    rm -rf /opt/bitnami/drupal/vendor
  else
    mv /opt/bitnami/drupal/vendor /bitnami/drupal/vendor
  fi
  ln -s /bitnami/drupal/vendor /opt/bitnami/drupal/vendor
  echo Created vendor symlink.;
  info "Starting drupal... "
fi

exec tini -- "$@"
```

You would need to manually create the container, and replace the Docker image in your chart or Docker Compose file.

I hope this works for you!

**Comment by marcosbc** [comment] 2018-08-20 11:52
Hi @scottrigby, we understand this is not a great solution but will work for now, until we fix the Drupal container.

The reason why it hasn't been fixed yet, is because it would break any kind of upgrade: If we persist the entire "htdocs" directory, the Drupal application will not be upgraded when changing the container version. If we persist only some files, dependencies might not get updated properly and therefore also break the application.

In any case, we already have an open internal task for fixing this, but unfortunately we don't have any ETA for when we will work on this.

**Comment by nastharl** [comment] 2019-04-23 20:09
@scottrigby This is super old now, but why make copies of the composer.lock and composer.json? If those have already been persisted into the /bitnami directory last time you ran the container, wont re-copying them blow away any changes that have been made since the last time the container started? The vendor directory moving wont remove anything old, but seems like composer.json and composer.lock would get screwed up.

Unless running composer update (Which doesn't currently work and i substituted composer install for) fixes that :(

**Comment by nastharl** [comment] 2019-04-23 22:43
Also - This solution doesn't work if the module in the vendor directory needs to be present in order for drupal to initialize in the first place (Which is the case for S3FS and who knows how many other modules out there)

**Comment by marcosbc** [comment] 2019-04-25 14:16
Hi @nastharl, the problem here is that `composer.lock` and `composer.json` are not being persisted into `/bitnami`.

Persisting these files is not a good idea, as it would break updates via changing the container version as mentioned in previous comments.

If users want to install custom Composer dependencies, the ideal approach is to fork the container and install the dependencies in `app-entrypoint.sh` (and not symlinking the vendor directory which was mentioned above).

**Comment by nastharl** [comment] 2019-04-25 15:41
The problem is that in app-entrypoint.sh, there's an initialization script that wipes the vendor directory clean. If I install something with composer BEFORE the initialization script, bitnami's initializer deletes it. If I install it AFTER the initializer, then it fails to initialize because it's not started. Install everything twice? is that the plan?

I'm really not sure why the vendor directory even gets deleted when bitnami's initializer runs. I tried symlinking vendor to the persisted filesystem so that when the initializer runs, it'll just add whatever it needs to the persisted directory, but that just resulted in it erasing the files inside the symlinked directory.

**Comment by marcosbc** [comment] 2019-04-26 14:46
Ideally the log should be executed right after the "nami_initialize" line.

> If I install it AFTER the initializer, then it fails to initialize because files it needs are missing.

Could you clarify what you mean with this? Composer dependency installation should work without issues at this stage.

>I'm really not sure why the vendor directory even gets deleted when bitnami's initializer runs. I tried symlinking vendor to the persisted filesystem so that when the initializer runs, it'll just add whatever it needs to the persisted directory, but that just resulted in it erasing the files inside the symlinked directory.

Note that you should move the vendor directory to the persisted directory after the "nami_initialize" line, and then symlink `/opt/bitnami/drupal/vendor` so it points to `/bitnami/drupal/vendor`.

If you do it like that, the vendor directory should not be emptied/overwritten (it did not according to some quick tests I made).

**Comment by nastharl** [comment] 2019-04-26 15:14
The s3fs module for storing files in S3 loads during initialization. As soon as it connects to the DB it tries to load classes from the module, which don't exist, and then the container immediately crashes before nami-initialize ever finishes. 

It might be a one-off that this module has the issue, but I don't want to risk every time I install a module that the server fails to boot.

**Comment by marcosbc** [comment] 2019-05-01 07:14
Hi @nastharl, in that case it is currently not possible to support that module, since "drush updatedb" is run right after the database connection is verified.

The only thing that occurs for me is for you to manually mount the "vendor" directory, "composer.lock" and "composer.json" (you will need to copy the files to the volume before), and then install the plugin.

The only problem with that is upgrading Drupal by changing the container version won't work, instead you will be forced to update it manually (via composer, drush or by extracting the new release tarball).

**Comment by nastharl** [comment] 2019-05-20 19:33
For what its worth, i tried that too, but the bitnami initialization process destroys my symlink and replaces it with a fresh directory.

**Comment by andresbono** [comment] 2019-05-21 11:01
Hi @nastharl, where in the [rootfs/app-entrypoint.sh](https://github.com/bitnami/bitnami-docker-drupal/blob/master/8/debian-9/rootfs/app-entrypoint.sh) are you creating the symlink?

**Comment by howtogithub-user** [comment] 2020-07-19 22:06
@marcosbc What do you mean by that? I am new to all this and it is confusing.

> If users want to install custom Composer dependencies, the ideal approach is to fork the container and install the dependencies in `app-entrypoint.sh` (and not symlinking the vendor directory which was mentioned above).

Isn't the reply you gave [here](https://github.com/bitnami/bitnami-docker-drupal/issues/93#issuecomment-413592779) correct?

I want to create a custom dockerfile for kubernetes using as a base image the bitnami one.
How shall I install the dependencies?

**Comment by marcosbc** [comment] 2020-07-20 16:47
Hi all (cc @howtogithub-user), we just wanted to let you know that we released a new container image that should make these changes easier.

Now, the initialization logic is based on Bash scripts, available in the `rootfs` repo of this repository. Read more on the changes here: https://github.com/bitnami/bitnami-docker-drupal#892-debian-10-r3-and-902-debian-10-r3

With these changes, it is now possible to manually specify the files that you want to persist via the `DRUPAL_DATA_TO_PERSIST` environment variable. Currently it is set to this (relative to `/opt/bitnami/drupal`):

    sites/ themes/ modules/ profiles/

You can modify it to set it to "/opt/bitnami/drupal" to persist the entire htdocs directory, or a specific list of files. We recommend to re-initialize drupal or to manually copy the files/dirs to the volume before using the new container image, to avoid errors restoring data.

Note that you may lose the ability to upgrade the application by changing the Docker container image if you do that, requiring you to upgrade it manually via CLI.

If you find it useful let us know. And if you feel there is any particular set of directories that should be added to the default list of directories to persist for the official image, please comment and we'll consider adding them.

**Comment by marcosbc** [comment] 2020-07-20 22:29
I'm going to close this issue, since it should be resolved now. However, if you consider that is not the case, let us know and we'll re-open.

**Closed by marcosbc** 2020-07-20 22:29 UTC
Labels: on-hold
